### PR TITLE
fix: fixed missing types for ArraySupport plugin

### LINKED ISSUE #1170: Typings for arraySupport missed
**Describe the bug**
arraySupport (https://github.com/iamkun/dayjs/issues/1129) lacks Typescript typings

**Expected behavior**
It should be possible to use arrays with typescript

**Information**
 - Day.js Version 1.9.4
 - OS: Win10
 - Browser Chrome
 - Time zone: GMT+3

### PR DESCRIPTION
**Pull request by JasonHK**
I've added an interface called `ConfigTypeMap`, so other plugins could add their own types to `ConfigType`. The same fix could be applied to ObjectSupport in a future pull request.

Fixes #1170

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -9,7 +9,11 @@ declare function dayjs (date?: dayjs.ConfigType, format?: dayjs.OptionType, stri
 declare function dayjs (date?: dayjs.ConfigType, format?: dayjs.OptionType, locale?: string, strict?: boolean): dayjs.Dayjs
 
 declare namespace dayjs {
-  export type ConfigType = string | number | Date | Dayjs
+  interface ConfigTypeMap {
+    default: string | number | Date | Dayjs
+  }
+
+  export type ConfigType = ConfigTypeMap[keyof ConfigTypeMap]
```
Comment (iamkun) [inline types/index.d.ts:16]: what's this used for please? And will this affect the original type if the plugin is imported?

Comment (JasonHK) [reply types/index.d.ts:16]: @iamkun The `type` keyword doesn't support [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). And yes, it will add the plugin's type into `ConfigType`.

`ConfigTypeMap[keyof ConfigTypeMap]` basically means "merge every members' type into a union". If no plugin was imported, the type of `ConfigType` is `string | number | Date | Dayjs` (same as before). When the ArraySupport plugin was imported, `ConfigType` will become `string | number | Date | Dayjs | [year?: number, ...]`.

Comment (iamkun) [reply types/index.d.ts:16]: looks cool, does this requires higher ts version?

Comment (JasonHK) [reply types/index.d.ts:16]: @iamkun Labeled tuple elements require TypeScript 4.0 or higher, I can convert it back to un-labelled ones if you want to support older TypeScript versions.

Comment (iamkun) [reply types/index.d.ts:16]: that's what I'm concerned. We should have a fallback support at least ts 3 I think

Comment (JasonHK) [reply types/index.d.ts:16]: @iamkun It should work on TypeScript 3 now.

Comment (iamkun) [reply types/index.d.ts:16]: can we make sure that `ConfigTypeMap[keyof ConfigTypeMap]` works on ts3?

Comment (JasonHK) [reply types/index.d.ts:16]: > can we make sure that `ConfigTypeMap[keyof ConfigTypeMap]` works on ts3?

@iamkun Yes, this will work on TypeScript 3. You can verify it on [TypeScript playground](https://www.typescriptlang.org/play?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgMpwLYAcA2ECycWAUAN7HKXIAmE8ArjmAFzIDOYUoA5sgD7IQ9DACNoAbgpUA9mAAW0VgBE4kSQF9ixMAE8sKdNjzIAvGky4CRANoBrCDukxzRq1gC6k4kA).

**Comment by iamkun** [comment]
THX
