### PR TITLE
Change string to number in duration object

### LINKED ISSUE #1389: Duration returns strings instead of numbers
**Describe the bug**
When parsing a duration string, eg `dayjs.duration('P1Y2M3W4DT12H34M56S')` and logging the result, it returns the values as strings instead of numbers:

image

**Expected behavior**
It should return numbers, as given by the return type in `plugins/duration.d.ts`.

**Information**
 - Day.js Version 1.10.4
 - OS: OSX 11.2.1
 - Browser: Chrome 88.0.4324.182
 - Time zone: GMT+7

### PR DESCRIPTION
**Pull request by mateuszpigula**
Fixes #1389 

I based on `parseFromMilliseconds` function.

I noticed there are already two failing tests:
```
 ● Convert › convert to target time

    expect(received).toBe(expected) // Object.is equality
    
    Expected value to be:
      1401624000000
    Received:
      1401620400000

```

### CODE REVIEW

File: src/plugin/duration/index.js [hunk 1]
```diff
@@ -79,15 +79,14 @@ class Duration {
     if (typeof input === 'string') {
       const d = input.match(durationRegex)
       if (d) {
-        [,,
```
Comment (iamkun) [inline src/plugin/duration/index.js:82]: let numberD = d.map(_=>Number(_))

will save some bytes I think

Comment (mateuszpigula) [reply src/plugin/duration/index.js:82]: Yep, great point @iamkun!

File: src/plugin/duration/index.js [hunk 2]
```diff
@@ -79,15 +79,17 @@ class Duration {
...
+        const [,, ...properties] = d
```
Comment (iamkun) [inline src/plugin/duration/index.js:82]: it is not advised to use `...` is dayjs cause it will compile to a lot es5 codes to make it work.

Comment (mateuszpigula) [reply src/plugin/duration/index.js:82]: It is worth mentioning in `CONTRIBUTING.md` as there is now: 
> Day.js is written in ES6.

**Comment by iamkun** [comment]
Cool
