### PR TITLE
fix: Allow customizing "am" / "pm" strings with locale meridiem function

### LINKED ISSUE #578: Allow customizing "am" / "pm" strings with locale
Some organizations specifically require the use of "a.m." and "p.m." instead of "am" and "pm". It would be very useful if the two strings could be customized using a custom locale -- they appear to be hard-coded right now.

### PR DESCRIPTION
**Pull request by iamkun**
fix #578

### CODE REVIEW

File: src/locale/ja.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ const locale = {
     lll: 'YYYY年M月D日 HH:mm',
     llll: 'YYYY年M月D日(ddd) HH:mm'
   },
```
Comment (muhammadridho) [inline src/locale/ja.js]: is it evey locale have this method ?

File: src/index.js [hunk 2]
```diff
@@ -305,8 +310,8 @@ class Dayjs {
       HH: Utils.s(this.$H, 2, '0'),
       h: get$H(1),
       hh: get$H(2),
-      a: this.$H < 12 ? 'am' : 'pm',
-      A: this.$H < 12 ? 'AM' : 'PM',
+      a: meridiemFunc(this.$H, this.$m, true),
```
Comment (muhammadridho) [inline src/index.js]: what if you change the name `a` into `am` thats readable object or key, wdyt ?

Comment (xxyuk) [reply src/index.js]: I think no. This lib is designed to keep the same with moment.js

File: src/locale/ja.js (hunk 1 above)
Comment (xxyuk) [reply src/locale/ja.js]: if locale need other than am/pm might need this. moment.js'locale file is a good reference

File: src/index.js (hunk 2 above)
Comment (muhammadridho) [reply src/index.js]: got it

File: src/locale/ja.js (hunk 1 above)
Comment (muhammadridho) [reply src/locale/ja.js]: lgtm, if we have updated documentation too 👍

**Comment by gka** [comment]
yay, thanks!
